[Reporter]
from_address = ""
spamcop_report_address = ""
# For testing and debugging:
#mock_report_address = ""
smtpd_address = ""

[Daemon]
watchdog_time = 15
maildir_base = ""
log_level = "WARNING"
force_root_override = false